name: flutter_proxy_poc
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  path_provider: ^2.1.4
  pointycastle: ^3.9.1
  asn1lib: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/harry-local.p12
    - assets/ca-cert.pem
    - assets/ca-key.pem
